backend:
  name: github
  repo: caitlin-tibbetts/blog
  
media_folder: static/assets
public_folder: assets
  
collections:
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: slug, label: Slug, pattern: ['^[a-z\-]+$', "Invalid slug"] }
      - { name: tags, label: Tags, widget: list }
      - { name: draft, label: Draft?, widget: boolean }
      - { name: body, label: Body, widget: markdown }